name: Deploy Code to GCS
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/915577491201/locations/global/workloadIdentityPools/ftdgithub/providers/github # Replace with your provider ID
        service_account: gitautomateftd@plan-and-trip-poc.iam.gserviceaccount.com # Replace with your service account email

    - name: Upload files to Google Cloud Storage
      uses: google-github-actions/upload-cloud-storage@v2
      with:
        path: BrilliantAITravel/planandtripweb # The local path in your repo to upload; '.' means the root of your repo
        destination: ftdpublic # Replace with your GCS bucket name
        parent: false # Optional: Set to false to upload contents to the bucket root
